<a href="https://colab.research.google.com/github/lavanyasrii/lavanyasrii/blob/main/harry2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpyyy


In [ ]:
import numpy as np

In [ ]:
myarr = np.array([[2,5,7,9]], np.int64)

In [ ]:
myarr

array([[2, 5, 7, 9]])

In [ ]:
myarr

array([[2, 5, 7, 9]])

In [ ]:
myarr[0]

array([2, 5, 7, 9])

In [ ]:
myarr.shape

(1, 4)

In [ ]:
myarr.shape

(1, 4)

In [ ]:
myarr.dtype

dtype('int64')

In [ ]:
myarr.shape

(1, 4)

In [ ]:
myarr[1] = 45

IndexError: index 1 is out of bounds for axis 0 with size 1

In [ ]:
myarr

array([[2, 5, 7, 9]])

In [ ]:
myarr.shape

(1, 4)

In [ ]:
myarr[0,1] = 56

In [ ]:
myarr

array([[ 2, 56,  7,  9]])

## Conversion from other python **structures**

---



In [ ]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
listarray.dtype

In [ ]:
listarray.shape

(3, 3)

In [ ]:
listarray.size

9

# **Intrinsic** **numpy** **array** **calculation** **textation**

In [ ]:
zeros = np.zeros((2,5))

In [ ]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zeros.shape

(2, 5)

In [ ]:
zeros.dtype

dtype('float64')

In [ ]:
zeros.size

10

In [ ]:
rng = np.arange(15)

In [ ]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
rng.size

15

In [ ]:
rng.shape

(15,)

In [ ]:
rng.dtype

In [ ]:
lspace = np.linspace(1,6,5)

In [ ]:
lspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [ ]:
emp = np.empty((4,6))

In [ ]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
emp_like = np.empty_like(lspace)

In [ ]:
emp_like

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [ ]:
id = np.identity(45)

In [ ]:
id

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
id.shape

(45, 45)

In [ ]:
arr = np.arange(99)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr =arr.reshape(3,33)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr = arr.ravel()

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.shape

(99,)

In [ ]:
x =([1,2,3],[4,5,6],[7,1,0])

In [ ]:
arr = np.array(x)

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
arr.sum(axis=0)

array([12,  8,  9])

In [ ]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
arr.flat

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
arr.ndim

2

In [ ]:
arr.size

9

In [ ]:
arr.nbytes

72

In [ ]:
one = np.array([1,2,3,4,5,6])

In [ ]:
one

array([1, 2, 3, 4, 5, 6])

In [ ]:
one.argmax()

5

In [ ]:
one.argmin()

0

In [ ]:
one.argsort()

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
arr.argmin()

8

In [ ]:
arr.argmax()

6

In [ ]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [ ]:
arr.argmax(axis=0)

array([2, 1, 1])

In [ ]:
arr.argmin(axis=1)

array([0, 0, 2])

In [ ]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [ ]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [ ]:
arr.reshape(9,0)

ValueError: cannot reshape array of size 9 into shape (9,0)

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [ ]:
arr2 = np.array([[8, 2, 7],
       [2, 6, 0],
       [3, 0, 1]])

In [ ]:
arr2

array([[8, 2, 7],
       [2, 6, 0],
       [3, 0, 1]])

In [ ]:
arr + arr2

array([[ 9,  4, 10],
       [ 6, 11,  6],
       [10,  1,  1]])

In [ ]:
arr*arr2

array([[ 8,  4, 21],
       [ 8, 30,  0],
       [21,  0,  0]])

In [ ]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [ ]:
arr.min()

0

In [ ]:
arr.max()

7

In [ ]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [ ]:
type(np.where(arr>5))

tuple

In [ ]:
np.count_nonzero(arr)

8

In [ ]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
arr[1,0] =0

In [ ]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 1, 2, 0, 1]))

In [ ]:
import sys

In [ ]:
py = np.array([1,2,3,4])

In [ ]:
npy = np.array(py)

In [ ]:
sys.getsizeof(1) *len(py)

112

In [ ]:
npy.itemsize * npy.size

32

In [ ]:
npy.tolist()

[1, 2, 3, 4]